#!/bin/sh
ip link set eth0 down
ip addr flush eth0

# =================================
# Setup interfaces and VLANs 
# =================================
ip link set eth0 up
# Create VLAN 101 on interface eth0: eth0.101
ip link add link eth0 name eth0.101 type vlan id 101
# Create bridge br0 with STP(0) on VLAN 101 with interfaces/tagged: 
# lan1 untag lan2 untag lan3 untag lan4 untag wan untag wlan0 untag eth0.101 tag
ip link add br0 type bridge
ip link set dev br0 type bridge stp_state 0

bridge vlan

ip link set lan1 master br0
bridge vlan add vid 101 dev lan1 pvid untagged
bridge vlan add vid 101 dev lan1 pvid untagged self
ip link set lan1 up

ip link set lan2 master br0
bridge vlan add vid 101 dev lan2 pvid untagged
bridge vlan add vid 101 dev lan2 pvid untagged self
ip link set lan2 up

ip link set lan3 master br0
bridge vlan add vid 101 dev lan3 pvid untagged
bridge vlan add vid 101 dev lan3 pvid untagged self
ip link set lan3 up

ip link set lan4 master br0
bridge vlan add vid 101 dev lan4 pvid untagged
bridge vlan add vid 101 dev lan4 pvid untagged self
ip link set lan4 up

ip link set wan master br0
bridge vlan add vid 101 dev wan pvid untagged
bridge vlan add vid 101 dev wan pvid untagged self
ip link set wan up

ip link set eth0.101 master br0
bridge vlan add vid 101 dev eth0.101 pvid untagged
bridge vlan add vid 101 dev eth0.101 pvid untagged self
ip link set eth0.101 up

bridge vlan

